### ISSUE TITLE
Liquigraph 3.1.0 throws error "java.lang.NoSuchFieldError: NULL" on startup when using neo4j-ogm version 3.2.1

### ISSUE THREAD

**Issue by lcichero** [liquibase/liquigraph#248]
_Which versions and flavour (CLI, Maven...) of Liquigraph are you using?_
**Maven 3.3.9 and Liquigraph 3.1.0**

_Which language (and which version of that language) are you developing with?_
**Java 8 and Java 11**

_What operating system are you on?_
**Windows Pro 10 64-bits**

_Are you working with a cluster or on a single machine?_
**Single machine**

_What code are you running?_
```
org.liquigraph.core.configuration.Configuration configuration = new ConfigurationBuilder()
                .withMasterChangelogLocation("db/liquigraph/changelog.xml")
                .withUri("jdbc:neo4j:" + databaseUrl)
                .withUsername(username)
                .withPassword(password)
                .withRunMode()
                .build();

        Liquigraph liquigraph = new Liquigraph();
        liquigraph.runMigrations(configuration);
```

_What errors are you seeing?_
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'runLiquigraphMigrations' defined in class path resource [nz/co/lionel/neo4ogmzoneddatetime/configuration/LiquigraphConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [void]: Factory method 'runLiquigraphMigrations' threw exception; nested exception is java.lang.NoSuchFieldError: NULL
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:475) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at nz.co.lionel.neo4ogmzoneddatetime.Neo4OgmZoneddatetimeApplication.main(Neo4OgmZoneddatetimeApplication.java:15) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [void]: Factory method 'runLiquigraphMigrations' threw exception; nested exception is java.lang.NoSuchFieldError: NULL
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.NoSuchFieldError: NULL
	at org.neo4j.driver.v1.Values.<clinit>(Values.java:59) ~[neo4j-jdbc-driver-3.1.0.jar:na]
	at org.neo4j.driver.v1.AuthTokens.basic(AuthTokens.java:45) ~[neo4j-jdbc-driver-3.1.0.jar:na]
	at org.neo4j.jdbc.bolt.BoltDriver.getAuthToken(BoltDriver.java:82) ~[neo4j-jdbc-driver-3.1.0.jar:na]
	at org.neo4j.jdbc.bolt.BoltDriver.connect(BoltDriver.java:64) ~[neo4j-jdbc-driver-3.1.0.jar:na]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:na]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251) ~[java.sql:na]
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri$UriToConnectionFunction.apply(ConnectionConfigurationByUri.java:80) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri$UriToConnectionFunction.apply(ConnectionConfigurationByUri.java:74) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:57) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:29) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:37) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:126) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:117) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:71) ~[liquigraph-core-3.1.0.jar:na]
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63) ~[liquigraph-core-3.1.0.jar:na]
	at nz.co.lionel.neo4ogmzoneddatetime.configuration.LiquigraphConfiguration.runLiquigraphMigrations(LiquigraphConfiguration.java:33) ~[classes/:na]
	at nz.co.lionel.neo4ogmzoneddatetime.configuration.LiquigraphConfiguration$$EnhancerBySpringCGLIB$$fb4b2937.CGLIB$runLiquigraphMigrations$0(<generated>) ~[classes/:na]
	at nz.co.lionel.neo4ogmzoneddatetime.configuration.LiquigraphConfiguration$$EnhancerBySpringCGLIB$$fb4b2937$$FastClassBySpringCGLIB$$791ce73f.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at nz.co.lionel.neo4ogmzoneddatetime.configuration.LiquigraphConfiguration$$EnhancerBySpringCGLIB$$fb4b2937.runLiquigraphMigrations(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 19 common frames omitted
```

_What solutions have you tried already?_
**I have tried different combinations of versions but none of them seems to work. Liquigraph seems to be working fine at least until neo4j-ogm version 3.1.15**

I have created an example project, you can download it from: https://github.com/lcichero/neo4j-ogm-zoneddatetime

**Comment by lcichero** [comment]
I've just found that it does not work over BOLT protocol but it does work over HTTP.

**Comment by ctytgat** [comment]
This is actually caused by 
https://github.com/neo4j-contrib/neo4j-jdbc/issues/208

There's an incompatibility between driver versions used by neo4j jdbc and ogm 3.2 ... :(

**Comment by lcichero** [comment]
> This is actually caused by
> [neo4j-contrib/neo4j-jdbc#208](https://github.com/neo4j-contrib/neo4j-jdbc/issues/208)
> 
> There's an incompatibility between driver versions used by neo4j jdbc and ogm 3.2 ... :(

Oh ok, so it is not a Liquigraph issue but rather an issue of its dependencies.
Should I close this issue and mention this neo4j-contrib/neo4j-jdbc/issues/208?

**Comment by fbiville** [comment]
You can keep this open, as we'll need to do something one way or another.

**Comment by ctytgat** [comment]
@fbiville Would it be an option to drop the jdbc driver and use the java bolt driver directly?

**Comment by fbiville** [comment]
@ctytgat we need to support HTTP as well. We could come up with our own wrappers for the native Bolt Java driver and Neo4j APIs but that seems a bit like reinventing the wheel.

**Comment by ctytgat** [comment]
Ok. According to the JDBC guys there should be a beta release this week.

**Comment by fbiville** [comment]
@ctytgat have you had a chance to test the JDBC release?
Also, I'm considering adding an OGM and a Spring Data Neo4j sample. Ideas are welcome :)

**Comment by ctytgat** [comment]
Hi, just noticed the 4.0.0 JDBC release, great! We don't use it directly, only through liquigraph...
Any idea of when we can expect a liquigraph update with this?

**Comment by fbiville** [comment]
I have a CI issue to take care of, but a 4.0 Release Candidate should be out next week, hopefully.

**Comment by fbiville** [comment]
Note there is also a recent 3.5.1 release for the JDBC driver that may work for you.
I just need to catch up on Neo4j 3.4 and 3.5 for Liquigraph 3.x.

**Comment by hfgbarrigas** [comment]
Hi, any news regarding this?

Currently using the following versions and experiencing the same issue:

neo4j-ogm: 3.2.11
neo4j-jdbc-bolt: 3.5.1
liquigraph: 3.1.2

**Comment by fbiville** [comment]
The latest release (https://github.com/liquibase/liquigraph/releases/tag/liquigraph-4.0.3) contains the JDBC fix.
