### ISSUE TITLE
CLI: JVM does't terminate when neo4j unavailable (version 4.0.0, bolt protocol and Jdk11)

### ISSUE THREAD

**Issue by gonzalad** [liquibase/liquigraph#375]
Hello,

When using the bolt protocol, the migration CLI hangs whenever the neo4j db is unavailable.

I'm executing my migrations with the following command line.

Am I doing something wrong ?

```
java -jar liquigraph-cli-4.0.0.jar --changelog "${your_project}/changelog.xml" \
    --graph-db-uri jdbc:neo4j:bolt://localhost:7687/ \
    --dry-run-output-directory /tmp
```

I'm using this jdk:

```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment 18.9 (build 11.0.5+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10, mixed mode)
```

I suspect the JVM is waiting for Netty threads to terminate (thing that doesn't happen).

Thanks,
Adrian

P.S.: Here are my logs if they can be of any help

```
21:44:36.933 [main] DEBUG org.liquigraph.core.io.xml.DomSourceValidatorFactory - No schema detected: validation against embedded schema to start
21:44:37.030 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
21:44:37.031 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
21:44:37.044 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
21:44:37.044 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
21:44:37.049 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
21:44:37.049 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
21:44:37.061 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
21:44:37.061 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - Java version: 11
21:44:37.062 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
21:44:37.062 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
21:44:37.063 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
21:44:37.064 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:225)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:219)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:273)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:279)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:150)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at org.neo4j.driver.internal.shaded.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:96)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:91)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at org.neo4j.driver.internal.async.connection.EventLoopGroupFactory$DriverEventLoopGroup.<init>(EventLoopGroupFactory.java:112)
	at org.neo4j.driver.internal.async.connection.EventLoopGroupFactory.newEventLoopGroup(EventLoopGroupFactory.java:68)
	at org.neo4j.driver.internal.async.connection.BootstrapFactory.newBootstrap(BootstrapFactory.java:33)
	at org.neo4j.driver.internal.DriverFactory.createBootstrap(DriverFactory.java:263)
	at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:80)
	at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:70)
	at org.neo4j.driver.GraphDatabase.driver(GraphDatabase.java:141)
	at org.neo4j.jdbc.bolt.BoltDriver.lambda$static$0(BoltDriver.java:46)
	at org.neo4j.jdbc.bolt.cache.BoltDriverCache.getDriver(BoltDriverCache.java:65)
	at org.neo4j.jdbc.bolt.BoltDriver.getDriver(BoltDriver.java:65)
	at org.neo4j.jdbc.bolt.impl.BoltNeo4jDriverImpl.connect(BoltNeo4jDriverImpl.java:92)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri$DefaultUriConnectionSupplier.getConnection(ConnectionConfigurationByUri.java:67)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:57)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:26)
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:43)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:121)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:111)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:65)
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:101)
	at org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:135)
21:44:37.065 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
21:44:37.065 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @5f354bcf
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:335)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:326)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:273)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:279)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:150)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at org.neo4j.driver.internal.shaded.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:96)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:91)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at org.neo4j.driver.internal.async.connection.EventLoopGroupFactory$DriverEventLoopGroup.<init>(EventLoopGroupFactory.java:112)
	at org.neo4j.driver.internal.async.connection.EventLoopGroupFactory.newEventLoopGroup(EventLoopGroupFactory.java:68)
	at org.neo4j.driver.internal.async.connection.BootstrapFactory.newBootstrap(BootstrapFactory.java:33)
	at org.neo4j.driver.internal.DriverFactory.createBootstrap(DriverFactory.java:263)
	at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:80)
	at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:70)
	at org.neo4j.driver.GraphDatabase.driver(GraphDatabase.java:141)
	at org.neo4j.jdbc.bolt.BoltDriver.lambda$static$0(BoltDriver.java:46)
	at org.neo4j.jdbc.bolt.cache.BoltDriverCache.getDriver(BoltDriverCache.java:65)
	at org.neo4j.jdbc.bolt.BoltDriver.getDriver(BoltDriver.java:65)
	at org.neo4j.jdbc.bolt.impl.BoltNeo4jDriverImpl.connect(BoltNeo4jDriverImpl.java:92)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri$DefaultUriConnectionSupplier.getConnection(ConnectionConfigurationByUri.java:67)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:57)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:26)
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:43)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:121)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:111)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:65)
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:101)
	at org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:135)
21:44:37.066 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
21:44:37.066 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
21:44:37.076 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - maxDirectMemory: 8386510848 bytes (maybe)
21:44:37.076 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
21:44:37.076 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
21:44:37.077 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
21:44:37.077 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
21:44:37.078 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
21:44:37.078 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
21:44:37.081 [main] DEBUG org.neo4j.driver.internal.shaded.io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
avr. 27, 2020 9:44:37 PM org.neo4j.driver.internal.logging.JULogger info
INFOS: Direct driver instance 1940055334 created for server address localhost:7687
Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to localhost:7687, ensure the database is running and that there is a working network connection to it.
	at org.liquigraph.core.exception.Throwables.propagate(Throwables.java:28)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri$DefaultUriConnectionSupplier.getConnection(ConnectionConfigurationByUri.java:69)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:57)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri.get(ConnectionConfigurationByUri.java:26)
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:43)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:121)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:111)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:65)
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:101)
	at org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:135)
Caused by: java.sql.SQLException: org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to localhost:7687, ensure the database is running and that there is a working network connection to it.
	at org.neo4j.jdbc.bolt.impl.BoltNeo4jDriverImpl.connect(BoltNeo4jDriverImpl.java:96)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.liquigraph.core.configuration.ConnectionConfigurationByUri$DefaultUriConnectionSupplier.getConnection(ConnectionConfigurationByUri.java:67)
	... 8 more
Caused by: org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to localhost:7687, ensure the database is running and that there is a working network connection to it.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:113)
	at org.neo4j.driver.internal.InternalDriver.verifyConnectivity(InternalDriver.java:159)
	at org.neo4j.jdbc.bolt.cache.BoltDriverCached.verifyConnectivity(BoltDriverCached.java:105)
	at org.neo4j.jdbc.bolt.impl.BoltNeo4jDriverImpl.connect(BoltNeo4jDriverImpl.java:93)
	... 11 more
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
		at org.neo4j.driver.internal.async.connection.ChannelConnectedListener.databaseUnavailableError(ChannelConnectedListener.java:76)
		at org.neo4j.driver.internal.async.connection.ChannelConnectedListener.operationComplete(ChannelConnectedListener.java:70)
		at org.neo4j.driver.internal.async.connection.ChannelConnectedListener.operationComplete(ChannelConnectedListener.java:37)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connexion refusée: localhost/127.0.0.1:7687
Caused by: java.net.ConnectException: Connexion refusée
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gonzalad** [comment]
I have no such issue with the bolt protocol with liquigraph 3.1.1 and jdk8

**Comment by fbiville** [comment]
Thanks for reporting this @gonzalad, I'll look into.
Out of curiosity, is there a particular reason you are running with `java -jar` and not using the official CLI?

**Comment by gonzalad** [comment]
ThanksFlorent !

> Out of curiosity, is there a particular reason you are running with java -jar and not using the official CLI

Only for testing reasons: I wanted to be sure to get the right exit status code. The class was called by a kubernetes init-task and I thought at first that the issue I had happened because the CLI was returning exist code 0. 

I should have known that since the init task was stuck that it was not an exist status code issue :)

**Comment by fbiville** [comment]
@gonzalad thanks for the bug report again. After investigation, this seems to be a JDBC driver issue, I just filed a bug [there](https://github.com/neo4j-contrib/neo4j-jdbc/issues/225)

**Comment by fbiville** [comment]
Just waiting for a JDBC release for this one.

**Comment by fbiville** [comment]
Hello, you could try the [4.0.3](https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/4.0.3) version of the JDBC driver and the problem should be gone.

**Comment by fbiville** [comment]
The fix has been merged, I will push another 4.x release once https://github.com/liquibase/liquigraph/pull/444 is merged. Thanks for the initial report!
